service:
  name: kopi-shops-api

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-plugin-common-excludes
  - serverless-plugin-canary-deployments

custom:
  stage: ${opt:stage, 'dev'}
  dev:
    domain: api-dev.simplepipeline.xyz
    certificate: arn:aws:acm:us-east-1:275307759108:certificate/d2e595ec-1d14-4363-a18b-834e21350cf3
    deploymentSettings:
      type: AllAtOnce
      alias: AllAtOnceDev

  prod:
    domain: api.simplepipeline.xyz
    certificate: arn:aws:acm:us-east-1:275307759108:certificate/e18e344d-1161-4ecf-b39a-eb316497dd82
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live10pctPerMinuteProd

  customDomain:
    domainName: ${self:custom.${self:custom.stage}.domain}
    certificateArn: ${self:custom.${self:custom.stage}.certificate}
    createRoute53Record: true
    basePath: shops

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  find:
    handler: shops/find.find
    events:
      - http:
          method: get
          path: /
          cors: true
          private: false
    deploymentSettings:
      type: ${self:custom.${self:custom.stage}.deploymentSettings.type}
      alias: ${self:custom.${self:custom.stage}.deploymentSettings.alias}

